=== Shopify/theme-liquid-docs/schemas/theme/section.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Shopify Liquid Theme Section Schema",
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "options": {
      "description": "Takes an array of `value`/`label` definitions.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "value": {
            "type": "string"
          },
          "label": {
            "type": "string"
          }
        },
        "required": ["value", "label"]
      }
    },
    "inputSettings": {
      "type": "array",
      "description": "Input settings can hold a value and are configurable by merchants.",
      "markdownDescription": "Input settings can hold a value and are configurable by merchants.\n\n---\n[Shopify reference](https://shopify.dev/docs/themes/architecture/settings/input-settings)",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "The unique identifier for the setting, which is used to access the setting value.",
            "markdownDescription": "The unique identifier for the setting, which is used to access the setting value.\n\n---\n[Shopify reference](https://shopify.dev/docs/themes/architecture/settings/input-settings#standard-attributes)"
          },
          "type": {
            "type": "string",
            "description": "The input type of the setting.",
            "markdownDescription": "The input type of the setting.\n\n---\n[Shopify reference](https://shopify.dev/docs/themes/architecture/settings/input-settings#standard-attributes)",
            "enum": [
              "article",
              "blog",
              "checkbox",
              "collection_list",
              "collection",
              "color_background",
              "color_scheme_group",
              "color_scheme",
              "color",
              "font_picker",
              "header",
              "html",
              "image_picker",
              "inline_richtext",
              "link_list",
              "liquid",
              "number",
              "page",
              "paragraph",
              "product_list",
              "product",
              "radio",
              "range",
              "richtext",
              "select",
              "text",
              "textarea",
              "text_alignment",
              "url",
              "video_url",
              "video"
            ]
          },
          "label": {
            "type": "string",
            "description": "The label for the setting, which will show in the theme editor."
          },
          "default": {
            "description": "The default value for the setting."
          },
          "info": {
            "type": "string",
            "description": "An option for informational text about the setting."
          }
        },
        "allOf": [
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["header", "paragraph"]
                }
              }
            },
            "then": {
              "required": ["type"]
            },
            "else": {
              "required": ["type", "id", "label"]
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["checkbox"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "boolean"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["number"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "number"
                },
                "placeholder": {
                  "type": "number",
                  "description": "A placeholder value for the input."
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["radio"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string",
                  "description": "The value of the default option"
                },
                "options": {
                  "$ref": "#/definitions/options"
                }
              },
              "required": ["options"]
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["range"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "number"
                },
                "min": {
                  "type": "number",
                  "description": "The minimum value of the input"
                },
                "max": {
                  "type": "number",
                  "description": "The maximum value of the input"
                },
                "step": {
                  "type": "number",
                  "description": "The increment size between steps of the slider"
                },
                "unit": {
                  "type": "string",
                  "description": "The unit for the input. For example, you can set \"px\" for a font-size slider",
                  "markdownDescription": "The unit for the input. For example, you can set `px` for a font-size slider"
                }
              },
              "required": ["min", "max", "step"]
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["select"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string",
                  "description": "The value of the default option"
                },
                "options": {
                  "$ref": "#/definitions/options"
                },
                "group": {
                  "type": "string",
                  "description": "An optional attribute that you can add to each option to create option groups in the drop-down."
                }
              },
              "required": ["options"]
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["text", "textarea", "html"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string"
                },
                "placeholder": {
                  "type": "string",
                  "description": "A placeholder value for the input."
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["liquid", "inline_richtext", "richtext", "url"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["collection_list", "product_list"]
                }
              }
            },
            "then": {
              "properties": {
                "limit": {
                  "type": "number",
                  "description": "The maximum number that the merchant can select. The default limit, and the maximum limit you can set, is 50."
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": [
                    "color",
                    "color_background",
                    "color_scheme",
                    "color_scheme_group",
                    "font_picker"
                  ]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["text_alignment"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string",
                  "enum": ["left", "right", "center"]
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["video_url"]
                }
              }
            },
            "then": {
              "properties": {
                "placeholder": {
                  "type": "string",
                  "description": "A placeholder value for the input."
                },
                "accept": {
                  "description": "Takes an array of accepted video providers. Valid values are youtube, vimeo, or both.",
                  "markdownDescription": "Takes an array of accepted video providers. Valid values are `youtube`, `vimeo`, or both.",
                  "type": "array",
                  "items": {
                    "type": "string",
                    "enum": ["youtube", "vimeo"]
                  }
                }
              },
              "required": ["accept"]
            }
          }
        ]
      },
      "minItems": 0
    },
    "sectionToggle": {
      "type": "object",
      "description": "Restrict the section to certain template page types and section group types.",
      "properties": {
        "templates": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "*",
              "404",
              "article",
              "blog",
              "captcha",
              "cart",
              "collection",
              "customers/account",
              "customers/activate_account",
              "customers/addresses",
              "customers/login",
              "customers/order",
              "customers/register",
              "customers/reset_password",
              "gift_card",
              "index",
              "list-collections",
              "metaobject",
              "page",
              "password",
              "policy",
              "product",
              "search"
            ]
          },
          "uniqueItems": true
        },
        "groups": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "name": {
      "type": "string",
      "description": "The section title shown in the theme editor."
    },
    "tag": {
      "type": "string",
      "description": "The HTML element to use for the section.",
      "enum": ["article", "aside", "div", "footer", "header", "section"]
    },
    "class": {
      "type": "string",
      "description": "Additional CSS class for the section."
    },
    "limit": {
      "type": "integer",
      "description": "The number of times a section can be added to a template or section group.",
      "minimum": 1,
      "maximum": 2
    },
    "settings": {
      "description": "Section specific settings.",
      "$ref": "#/definitions/inputSettings"
    },
    "max_blocks": {
      "type": "integer",
      "description": "The maximum number of blocks allowed in the section.",
      "minimum": 1,
      "maximum": 50
    },
    "blocks": {
      "type": "array",
      "description": "Section blocks.",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The block name."
          },
          "type": {
            "type": "string",
            "description": "The block type."
          },
          "settings": {
            "description": "Block settings.",
            "$ref": "#/definitions/inputSettings"
          }
        },
        "if": {
          "properties": {
            "type": {
              "const": "@app"
            }
          }
        },
        "then": {
          "required": ["type"]
        },
        "else": {
          "required": ["name", "type"]
        }
      }
    },
    "presets": {
      "type": "array",
      "description": "Section presets.",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The preset name."
          },
          "settings": {
            "type": "object",
            "description": "Default values for settings.",
            "additionalProperties": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "boolean"
                },
                {
                  "type": "string"
                },
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              ]
            }
          },
          "blocks": {
            "type": "array",
            "description": "Default blocks.",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "description": "The block type."
                },
                "settings": {
                  "type": "object",
                  "description": "Block settings.",
                  "additionalProperties": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "boolean"
                      },
                      {
                        "type": "string"
                      },
                      {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    ]
                  }
                }
              },
              "required": ["type"]
            }
          }
        },
        "required": ["name"]
      }
    },
    "default": {
      "type": "object",
      "description": "Default configuration for statically rendered sections.",
      "properties": {
        "settings": {
          "type": "object",
          "description": "Default values for settings.",
          "additionalProperties": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "boolean"
              },
              {
                "type": "string"
              },
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            ]
          }
        },
        "blocks": {
          "type": "array",
          "description": "Default blocks.",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "description": "The block type."
              },
              "settings": {
                "type": "object",
                "description": "Block settings.",
                "additionalProperties": {
                  "anyOf": [
                    {
                      "type": "number"
                    },
                    {
                      "type": "boolean"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  ]
                }
              }
            },
            "required": ["type"]
          }
        }
      }
    },
    "locales": {
      "type": "object",
      "description": "A set of translated strings for the section.",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      }
    },
    "enabled_on": {
      "description": "Restrict the section to certain template page types and section group types.",
      "$ref": "#/definitions/sectionToggle"
    },
    "disabled_on": {
      "description": "Prevent the section from being used on certain template page types and section group types.",
      "$ref": "#/definitions/sectionToggle"
    }
  }
}

=== Shopify/theme-liquid-docs/tests/fixtures/section-schema-4.json
{
  "name": "t:sections.slideshow.name",
  "tag": "section",
  "class": "section",
  "disabled_on": {
    "groups": ["header", "footer"]
  },
  "settings": [
    {
      "type": "select",
      "id": "layout",
      "options": [
        {
          "value": "full_bleed",
          "label": "t:sections.slideshow.settings.layout.options__1.label"
        },
        {
          "value": "grid",
          "label": "t:sections.slideshow.settings.layout.options__2.label"
        }
      ],
      "default": "full_bleed",
      "label": "t:sections.slideshow.settings.layout.label"
    },
    {
      "type": "select",
      "id": "slide_height",
      "options": [
        {
          "value": "adapt_image",
          "label": "t:sections.slideshow.settings.slide_height.options__1.label"
        },
        {
          "value": "small",
          "label": "t:sections.slideshow.settings.slide_height.options__2.label"
        },
        {
          "value": "medium",
          "label": "t:sections.slideshow.settings.slide_height.options__3.label"
        },
        {
          "value": "large",
          "label": "t:sections.slideshow.settings.slide_height.options__4.label"
        }
      ],
      "default": "medium",
      "label": "t:sections.slideshow.settings.slide_height.label"
    },
    {
      "type": "select",
      "id": "slider_visual",
      "options": [
        {
          "value": "dots",
          "label": "t:sections.slideshow.settings.slider_visual.options__2.label"
        },
        {
          "value": "counter",
          "label": "t:sections.slideshow.settings.slider_visual.options__1.label"
        },
        {
          "value": "numbers",
          "label": "t:sections.slideshow.settings.slider_visual.options__3.label"
        }
      ],
      "default": "counter",
      "label": "t:sections.slideshow.settings.slider_visual.label"
    },
    {
      "type": "checkbox",
      "id": "auto_rotate",
      "label": "t:sections.slideshow.settings.auto_rotate.label",
      "default": false
    },
    {
      "type": "range",
      "id": "change_slides_speed",
      "min": 3,
      "max": 9,
      "step": 2,
      "unit": "s",
      "label": "t:sections.slideshow.settings.change_slides_speed.label",
      "default": 5
    },
    {
      "type": "header",
      "content": "t:sections.all.animation.content"
    },
    {
      "type": "select",
      "id": "image_behavior",
      "options": [
        {
          "value": "none",
          "label": "t:sections.all.animation.image_behavior.options__1.label"
        },
        {
          "value": "ambient",
          "label": "t:sections.all.animation.image_behavior.options__2.label"
        }
      ],
      "default": "none",
      "label": "t:sections.all.animation.image_behavior.label"
    },
    {
      "type": "header",
      "content": "t:sections.slideshow.settings.mobile.content"
    },
    {
      "type": "checkbox",
      "id": "show_text_below",
      "label": "t:sections.slideshow.settings.show_text_below.label",
      "default": true
    },
    {
      "type": "header",
      "content": "t:sections.slideshow.settings.accessibility.content"
    },
    {
      "type": "text",
      "id": "accessibility_info",
      "label": "t:sections.slideshow.settings.accessibility.label",
      "info": "t:sections.slideshow.settings.accessibility.info",
      "default": "Slideshow about our brand"
    }
  ],
  "blocks": [
    {
      "type": "slide",
      "name": "t:sections.slideshow.blocks.slide.name",
      "limit": 5,
      "settings": [
        {
          "type": "image_picker",
          "id": "image",
          "label": "t:sections.slideshow.blocks.slide.settings.image.label"
        },
        {
          "type": "inline_richtext",
          "id": "heading",
          "default": "Image slide",
          "label": "t:sections.slideshow.blocks.slide.settings.heading.label"
        },
        {
          "type": "select",
          "id": "heading_size",
          "options": [
            {
              "value": "h2",
              "label": "t:sections.all.heading_size.options__1.label"
            },
            {
              "value": "h1",
              "label": "t:sections.all.heading_size.options__2.label"
            },
            {
              "value": "h0",
              "label": "t:sections.all.heading_size.options__3.label"
            }
          ],
          "default": "h1",
          "label": "t:sections.all.heading_size.label"
        },
        {
          "type": "inline_richtext",
          "id": "subheading",
          "default": "Tell your brand's story through images",
          "label": "t:sections.slideshow.blocks.slide.settings.subheading.label"
        },
        {
          "type": "text",
          "id": "button_label",
          "default": "Button label",
          "label": "t:sections.slideshow.blocks.slide.settings.button_label.label",
          "info": "t:sections.slideshow.blocks.slide.settings.button_label.info"
        },
        {
          "type": "url",
          "id": "link",
          "label": "t:sections.slideshow.blocks.slide.settings.link.label"
        },
        {
          "type": "checkbox",
          "id": "button_style_secondary",
          "label": "t:sections.slideshow.blocks.slide.settings.secondary_style.label",
          "default": false
        },
        {
          "type": "select",
          "id": "box_align",
          "options": [
            {
              "value": "top-left",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__1.label"
            },
            {
              "value": "top-center",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__2.label"
            },
            {
              "value": "top-right",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__3.label"
            },
            {
              "value": "middle-left",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__4.label"
            },
            {
              "value": "middle-center",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__5.label"
            },
            {
              "value": "middle-right",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__6.label"
            },
            {
              "value": "bottom-left",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__7.label"
            },
            {
              "value": "bottom-center",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__8.label"
            },
            {
              "value": "bottom-right",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__9.label"
            }
          ],
          "default": "middle-center",
          "label": "t:sections.slideshow.blocks.slide.settings.box_align.label",
          "info": "t:sections.slideshow.blocks.slide.settings.box_align.info"
        },
        {
          "type": "checkbox",
          "id": "show_text_box",
          "label": "t:sections.slideshow.blocks.slide.settings.show_text_box.label",
          "default": true
        },
        {
          "type": "select",
          "id": "text_alignment",
          "options": [
            {
              "value": "left",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment.option_1.label"
            },
            {
              "value": "center",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment.option_2.label"
            },
            {
              "value": "right",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment.option_3.label"
            }
          ],
          "default": "center",
          "label": "t:sections.slideshow.blocks.slide.settings.text_alignment.label"
        },
        {
          "type": "range",
          "id": "image_overlay_opacity",
          "min": 0,
          "max": 100,
          "step": 10,
          "unit": "%",
          "label": "t:sections.slideshow.blocks.slide.settings.image_overlay_opacity.label",
          "default": 0
        },
        {
          "type": "color_scheme",
          "id": "color_scheme",
          "label": "t:sections.all.colors.label",
          "default": "background-1"
        },
        {
          "type": "header",
          "content": "t:sections.slideshow.settings.mobile.content"
        },
        {
          "type": "select",
          "id": "text_alignment_mobile",
          "options": [
            {
              "value": "left",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment_mobile.options__1.label"
            },
            {
              "value": "center",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment_mobile.options__2.label"
            },
            {
              "value": "right",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment_mobile.options__3.label"
            }
          ],
          "default": "center",
          "label": "t:sections.slideshow.blocks.slide.settings.text_alignment_mobile.label"
        }
      ]
    }
  ],
  "presets": [
    {
      "name": "t:sections.slideshow.presets.name",
      "blocks": [
        {
          "type": "slide"
        },
        {
          "type": "slide"
        }
      ]
    }
  ]
}
