=== Shopify/theme-liquid-docs/schemas/theme/section.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Shopify Liquid Theme Section Schema",
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "options": {
      "description": "Takes an array of `value`/`label` definitions.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "value": {
            "type": "string"
          },
          "label": {
            "type": "string"
          }
        },
        "required": ["value", "label"]
      }
    },
    "inputSettings": {
      "type": "array",
      "description": "Input settings can hold a value and are configurable by merchants.",
      "markdownDescription": "Input settings can hold a value and are configurable by merchants.\n\n---\n[Shopify reference](https://shopify.dev/docs/themes/architecture/settings/input-settings)",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "The unique identifier for the setting, which is used to access the setting value.",
            "markdownDescription": "The unique identifier for the setting, which is used to access the setting value.\n\n---\n[Shopify reference](https://shopify.dev/docs/themes/architecture/settings/input-settings#standard-attributes)"
          },
          "type": {
            "type": "string",
            "description": "The input type of the setting.",
            "markdownDescription": "The input type of the setting.\n\n---\n[Shopify reference](https://shopify.dev/docs/themes/architecture/settings/input-settings#standard-attributes)",
            "enum": [
              "article",
              "blog",
              "checkbox",
              "collection_list",
              "collection",
              "color_background",
              "color_scheme_group",
              "color_scheme",
              "color",
              "font_picker",
              "header",
              "html",
              "image_picker",
              "inline_richtext",
              "link_list",
              "liquid",
              "number",
              "page",
              "paragraph",
              "product_list",
              "product",
              "radio",
              "range",
              "richtext",
              "select",
              "text",
              "textarea",
              "text_alignment",
              "url",
              "video_url",
              "video"
            ]
          },
          "label": {
            "type": "string",
            "description": "The label for the setting, which will show in the theme editor."
          },
          "default": {
            "description": "The default value for the setting."
          },
          "info": {
            "type": "string",
            "description": "An option for informational text about the setting."
          }
        },
        "allOf": [
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["header", "paragraph"]
                }
              }
            },
            "then": {
              "required": ["type"]
            },
            "else": {
              "required": ["type", "id", "label"]
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["checkbox"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "boolean"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["number"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "number"
                },
                "placeholder": {
                  "type": "number",
                  "description": "A placeholder value for the input."
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["radio"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string",
                  "description": "The value of the default option"
                },
                "options": {
                  "$ref": "#/definitions/options"
                }
              },
              "required": ["options"]
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["range"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "number"
                },
                "min": {
                  "type": "number",
                  "description": "The minimum value of the input"
                },
                "max": {
                  "type": "number",
                  "description": "The maximum value of the input"
                },
                "step": {
                  "type": "number",
                  "description": "The increment size between steps of the slider"
                },
                "unit": {
                  "type": "string",
                  "description": "The unit for the input. For example, you can set \"px\" for a font-size slider",
                  "markdownDescription": "The unit for the input. For example, you can set `px` for a font-size slider"
                }
              },
              "required": ["min", "max", "step"]
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["select"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string",
                  "description": "The value of the default option"
                },
                "options": {
                  "$ref": "#/definitions/options"
                },
                "group": {
                  "type": "string",
                  "description": "An optional attribute that you can add to each option to create option groups in the drop-down."
                }
              },
              "required": ["options"]
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["text", "textarea", "html"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string"
                },
                "placeholder": {
                  "type": "string",
                  "description": "A placeholder value for the input."
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["liquid", "inline_richtext", "richtext", "url"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["collection_list", "product_list"]
                }
              }
            },
            "then": {
              "properties": {
                "limit": {
                  "type": "number",
                  "description": "The maximum number that the merchant can select. The default limit, and the maximum limit you can set, is 50."
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": [
                    "color",
                    "color_background",
                    "color_scheme",
                    "color_scheme_group",
                    "font_picker"
                  ]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["text_alignment"]
                }
              }
            },
            "then": {
              "properties": {
                "default": {
                  "type": "string",
                  "enum": ["left", "right", "center"]
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "enum": ["video_url"]
                }
              }
            },
            "then": {
              "properties": {
                "placeholder": {
                  "type": "string",
                  "description": "A placeholder value for the input."
                },
                "accept": {
                  "description": "Takes an array of accepted video providers. Valid values are youtube, vimeo, or both.",
                  "markdownDescription": "Takes an array of accepted video providers. Valid values are `youtube`, `vimeo`, or both.",
                  "type": "array",
                  "items": {
                    "type": "string",
                    "enum": ["youtube", "vimeo"]
                  }
                }
              },
              "required": ["accept"]
            }
          }
        ]
      },
      "minItems": 0
    },
    "sectionToggle": {
      "type": "object",
      "description": "Restrict the section to certain template page types and section group types.",
      "properties": {
        "templates": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "*",
              "404",
              "article",
              "blog",
              "captcha",
              "cart",
              "collection",
              "customers/account",
              "customers/activate_account",
              "customers/addresses",
              "customers/login",
              "customers/order",
              "customers/register",
              "customers/reset_password",
              "gift_card",
              "index",
              "list-collections",
              "metaobject",
              "page",
              "password",
              "policy",
              "product",
              "search"
            ]
          },
          "uniqueItems": true
        },
        "groups": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "name": {
      "type": "string",
      "description": "The section title shown in the theme editor."
    },
    "tag": {
      "type": "string",
      "description": "The HTML element to use for the section.",
      "enum": ["article", "aside", "div", "footer", "header", "section"]
    },
    "class": {
      "type": "string",
      "description": "Additional CSS class for the section."
    },
    "limit": {
      "type": "integer",
      "description": "The number of times a section can be added to a template or section group.",
      "minimum": 1,
      "maximum": 2
    },
    "settings": {
      "description": "Section specific settings.",
      "$ref": "#/definitions/inputSettings"
    },
    "max_blocks": {
      "type": "integer",
      "description": "The maximum number of blocks allowed in the section.",
      "minimum": 1,
      "maximum": 50
    },
    "blocks": {
      "type": "array",
      "description": "Section blocks.",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The block name."
          },
          "type": {
            "type": "string",
            "description": "The block type."
          },
          "settings": {
            "description": "Block settings.",
            "$ref": "#/definitions/inputSettings"
          }
        },
        "if": {
          "properties": {
            "type": {
              "const": "@app"
            }
          }
        },
        "then": {
          "required": ["type"]
        },
        "else": {
          "required": ["name", "type"]
        }
      }
    },
    "presets": {
      "type": "array",
      "description": "Section presets.",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The preset name."
          },
          "settings": {
            "type": "object",
            "description": "Default values for settings.",
            "additionalProperties": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "boolean"
                },
                {
                  "type": "string"
                },
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              ]
            }
          },
          "blocks": {
            "type": "array",
            "description": "Default blocks.",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "description": "The block type."
                },
                "settings": {
                  "type": "object",
                  "description": "Block settings.",
                  "additionalProperties": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "boolean"
                      },
                      {
                        "type": "string"
                      },
                      {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    ]
                  }
                }
              },
              "required": ["type"]
            }
          }
        },
        "required": ["name"]
      }
    },
    "default": {
      "type": "object",
      "description": "Default configuration for statically rendered sections.",
      "properties": {
        "settings": {
          "type": "object",
          "description": "Default values for settings.",
          "additionalProperties": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "boolean"
              },
              {
                "type": "string"
              },
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            ]
          }
        },
        "blocks": {
          "type": "array",
          "description": "Default blocks.",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "description": "The block type."
              },
              "settings": {
                "type": "object",
                "description": "Block settings.",
                "additionalProperties": {
                  "anyOf": [
                    {
                      "type": "number"
                    },
                    {
                      "type": "boolean"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  ]
                }
              }
            },
            "required": ["type"]
          }
        }
      }
    },
    "locales": {
      "type": "object",
      "description": "A set of translated strings for the section.",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      }
    },
    "enabled_on": {
      "description": "Restrict the section to certain template page types and section group types.",
      "$ref": "#/definitions/sectionToggle"
    },
    "disabled_on": {
      "description": "Prevent the section from being used on certain template page types and section group types.",
      "$ref": "#/definitions/sectionToggle"
    }
  }
}

=== Shopify/theme-liquid-docs/tests/fixtures/section-schema-2.json
{
  "name": "t:sections.collage.name",
  "tag": "section",
  "class": "section",
  "disabled_on": {
    "groups": ["header", "footer"]
  },
  "settings": [
    {
      "type": "inline_richtext",
      "id": "heading",
      "default": "Multimedia collage",
      "label": "t:sections.collage.settings.heading.label"
    },
    {
      "type": "select",
      "id": "heading_size",
      "options": [
        {
          "value": "h2",
          "label": "t:sections.all.heading_size.options__1.label"
        },
        {
          "value": "h1",
          "label": "t:sections.all.heading_size.options__2.label"
        },
        {
          "value": "h0",
          "label": "t:sections.all.heading_size.options__3.label"
        }
      ],
      "default": "h1",
      "label": "t:sections.all.heading_size.label"
    },
    {
      "type": "select",
      "id": "desktop_layout",
      "options": [
        {
          "value": "left",
          "label": "t:sections.collage.settings.desktop_layout.options__1.label"
        },
        {
          "value": "right",
          "label": "t:sections.collage.settings.desktop_layout.options__2.label"
        }
      ],
      "default": "left",
      "label": "t:sections.collage.settings.desktop_layout.label"
    },
    {
      "type": "select",
      "id": "mobile_layout",
      "options": [
        {
          "value": "collage",
          "label": "t:sections.collage.settings.mobile_layout.options__1.label"
        },
        {
          "value": "column",
          "label": "t:sections.collage.settings.mobile_layout.options__2.label"
        }
      ],
      "default": "column",
      "label": "t:sections.collage.settings.mobile_layout.label"
    },
    {
      "type": "select",
      "id": "card_styles",
      "options": [
        {
          "value": "none",
          "label": "t:sections.collage.settings.card_styles.options__1.label"
        },
        {
          "value": "product-card-wrapper",
          "label": "t:sections.collage.settings.card_styles.options__2.label"
        }
      ],
      "default": "product-card-wrapper",
      "info": "t:sections.collage.settings.card_styles.info",
      "label": "t:sections.collage.settings.card_styles.label"
    },
    {
      "type": "color_scheme",
      "id": "color_scheme",
      "label": "t:sections.all.colors.label",
      "info": "t:sections.all.colors.has_cards_info",
      "default": "background-1"
    },
    {
      "type": "header",
      "content": "t:sections.all.padding.section_padding_heading"
    },
    {
      "type": "range",
      "id": "padding_top",
      "min": 0,
      "max": 100,
      "step": 4,
      "unit": "px",
      "label": "t:sections.all.padding.padding_top",
      "default": 36
    },
    {
      "type": "range",
      "id": "padding_bottom",
      "min": 0,
      "max": 100,
      "step": 4,
      "unit": "px",
      "label": "t:sections.all.padding.padding_bottom",
      "default": 36
    }
  ],
  "blocks": [
    {
      "type": "image",
      "name": "t:sections.collage.blocks.image.name",
      "settings": [
        {
          "type": "image_picker",
          "id": "image",
          "label": "t:sections.collage.blocks.image.settings.image.label"
        }
      ]
    },
    {
      "type": "product",
      "name": "t:sections.collage.blocks.product.name",
      "settings": [
        {
          "type": "product",
          "id": "product",
          "label": "t:sections.collage.blocks.product.settings.product.label"
        },
        {
          "type": "checkbox",
          "id": "second_image",
          "default": false,
          "label": "t:sections.collage.blocks.product.settings.second_image.label"
        }
      ]
    },
    {
      "type": "collection",
      "name": "t:sections.collage.blocks.collection.name",
      "settings": [
        {
          "type": "collection",
          "id": "collection",
          "label": "t:sections.collage.blocks.collection.settings.collection.label"
        }
      ]
    },
    {
      "type": "video",
      "name": "t:sections.collage.blocks.video.name",
      "settings": [
        {
          "type": "image_picker",
          "id": "cover_image",
          "label": "t:sections.collage.blocks.video.settings.cover_image.label"
        },
        {
          "type": "video_url",
          "id": "video_url",
          "accept": ["youtube", "vimeo"],
          "default": "https://www.youtube.com/watch?v=_9VUPq3SxOc",
          "label": "t:sections.collage.blocks.video.settings.video_url.label",
          "placeholder": "t:sections.collage.blocks.video.settings.video_url.placeholder",
          "info": "t:sections.collage.blocks.video.settings.video_url.info"
        },
        {
          "type": "text",
          "id": "description",
          "default": "Describe the video",
          "label": "t:sections.collage.blocks.video.settings.description.label",
          "info": "t:sections.collage.blocks.video.settings.description.info"
        }
      ]
    }
  ],
  "max_blocks": 3,
  "presets": [
    {
      "name": "t:sections.collage.presets.name",
      "blocks": [
        {
          "type": "image"
        },
        {
          "type": "product"
        },
        {
          "type": "collection"
        }
      ]
    }
  ]
}
